/* eslint-disable @next/next/no-sync-scripts */
import PhaseBanner from "./_components/PhaseBanner";
import "node_modules/govuk-frontend/govuk/all";
import { Footer } from "./_components/Footer";
import { Header } from "./_components/Header";
import Cookie from "./_components/cookie";
import { Inter } from "next/font/google";
import type { Metadata } from "next";
import "./globals.css";
import "./main.scss";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Cookie />
        <Header />
        <PhaseBanner />
        {children}
        <Footer />
        <script src="govuk/govuk.js"></script>
      </body>
    </html>
  );
}
